name: App

on:
  push:
    branches:
      - main
jobs:
  Docker:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"
          POSTGRES_DB: "turbo_db"

        ports:
          - 5432:5432

        options: --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
     
      - name: Clean Docker container
        run: docker stop $(docker ps -a -q)
        
      - name: Run container App
        run: docker compose up -d
      
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: Install dependencies
        run:  cd frontend && npm install
      - name: Install Jest globally
        run:  cd frontend && sudo npm install -g jest
      - name: Run Tests
        run:  cd frontend && npm run test
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      
    




      
